install: make install
language: 'php'
php:
    - '5.4'
    - '5.5'
    - '5.6'
script: 'make test'
addons:
    code_climate:
        repo_token: '6fe40ad4db7325cd23ffce1fa21af391ae264a87c1d0ee0e17c36764a96ac61c'
after_script:
    - CODECLIMATE_REPO_TOKEN="6fe40ad4db7325cd23ffce1fa21af391ae264a87c1d0ee0e17c36764a96ac61c" vendor/bin/test-reporter --stdout > codeclimate.json
    - curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports