install: make install
language: 'php'
php:
    - '5.4'
    - '5.5'
    - '5.6'
script: 'make test'
addons:
    code_climate:
        repo_token: '6fe40ad4db7325cd23ffce1fa21af391ae264a87c1d0ee0e17c36764a96ac61c'
after_script:
    - './vendor/bin/test-reporter --coverage-report ./dist/php-coverage-clover.xml'