install: make install
language: 'php'
php:
    - '5.4'
    - '5.5'
    - '5.6'
script: 'make test'
after_script: 'php ./dist/deps/php/bin/test-reporter --coverage-report ./dist/php-coverage-clover.xml'
addons:
    code_climate:
        repo_token: 'd8e26171a1912c22238cf7c48e83f8561c4befc07ed6d706157e1b47f21878fa'